name: Track github issues

on: 
  issues:
    types: 
      - opened
      # [opened, edited, closed, milestoned]

jobs:
  show_issue:
    name: Show issue information
    runs-on: ubuntu-latest
    steps:
      - name: Print issue information
        run: echo "${{ toJSON(github) }}"
